### ISSUE TITLE
Confusion regarding bug position

### ISSUE THREAD

**Issue by mou23** [SerVal-DTF/AVATAR#1]
In the paper, it is mentioned that the faulty locations are calculated based on the ground truth of developer patches. However, for the bug _Closure 114_, the modified line no is _578_ (as shown in https://github.com/program-repair/defects4j-dissection/commit/714c5bd), whereas it is _585_ according to the _BugPositions.txt_ file.
Similar cases occur for bug _Closure 107_, _Lang_21_, etc.

Besides, the _BugPositions.txt_ file. of [AVATAR ](https://raw.githubusercontent.com/SerVal-DTF/AVATAR/master/BugPositions.txt) differs from that of [FL-VS-APR](https://raw.githubusercontent.com/SerVal-DTF/FL-VS-APR/master/data/BugPositions.txt). For example, _Closure_15_, _Chart_25_ etc.

Can you please help me in this regard? Thanks in advance.

**Comment by Kui-Liu** [comment]
Hello @mou23,

For Closure-114, its patch
"} else if (!(parent.isCall() && parent.getFirstChild() == n)) {
     recordDepScope(recordNode, ns);
}" is equal to 
"} else {
      if (!(parent.isCall() && parent.getFirstChild() == n)) {
           recordDepScope(recordNode, ns);
      }
}".
It is adding an if-check-statement for the line-578, so we consider the line-578 as buggy line.

For Closure-107, it is hard to decide the exact buggy line.
By considering the comments before line-861, only one code line in the block and "new EmptyMessageBundle();" assigned in the code line, we consider the line-861 as buggy line.

For Lang-21, lines 262-269 are for one statement, we are not sure that the line 265 can be identified as the buggy line since it is just one expression of the buggy statement. Therefore, we consider all lines of the buggy statement as buggy lines.

We had further discussion about the buggy positions, the data for FL-VS-APR is updated accordingly, we forgot to update the data in AVATAR.

**Comment by mou23** [comment]
Thank you so much @BruceKuiLiu for your valuable response. Now, these cases are clear to me. By the way, you mentioned that for Closure-114, line-578 should be considered as the buggy line. However, according to your file, the buggy location is 585. It would be helpful if you update it. Once again thank you so much.

**Comment by Kui-Liu** [comment]
Sorry for the typo "Line-578", it should be Line-585.

**Comment by mou23** [comment]
Won't it be more appropriate if you add both 578 and 585 as faulty lines as you did in _Math-10_?
![image](https://user-images.githubusercontent.com/24643588/88669213-6e12f800-d105-11ea-88ac-e610d92b27f4.png)

**Comment by Kui-Liu** [comment]
Yeah, maybe.

**Comment by mou23** [comment]
Okay. Thank you so much for your help :smiley:
